pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
	resolutionStrategy {
		eachPlugin {
			if (requested.id.id == 'net.fabricmc.fabric-loom'
					|| requested.id.id == 'net.fabricmc.fabric-loom-remap') {
				useModule("net.fabricmc:fabric-loom:${requested.version}")
			}
		}
	}
}

// Should match your modid
rootProject.name = 'villagebuff'
